<p>This is <b>about</b> a php language description  page.PHP is an acronym for "PHP: Hypertext Preprocessor"<b>
PHP is a widely-used, open source scripting language<b>
PHP scripts are executed on the server<b>
PHP is free to download and use </p>
<p>It is powerful enough to be at the core of the biggest blogging system on the web (WordPress)!
It is deep enough to run the largest social network (Facebook)!
It is also easy enough to be a beginner's first server side language!<b>
  A comment in PHP code is a line that is not executed as a part of the program. Its only purpose is to be read by someone who is looking at the code.In PHP, a variable starts with the $ sign, followed by the name of the variable.Variables can store data of different types, and different data types can do different things.

PHP supports the following data types:

String
Integer
Float (floating point numbers - also called double)
Boolean
Array
Object
NULL
Resource
  </p>
